platform :ios, '12.0'
use_frameworks!

project 'nRF Connect Device Manager'

target 'nRF Connect Device Manager' do
  pod 'iOSMcuManagerLibrary', :path => '../iOSMcuManagerLibrary/'
  pod 'iOSOtaLibrary', :path => '../iOSOtaLibrary/'
end
